using System.Text;

using Microsoft.OpenApi;

namespace OpenApiClientGenerator;

public sealed partial class OpenApiClientSourceGenerator
{
    private sealed partial class ClientEmitter
    {
        private static readonly HashSet<string> s_reservedIdentifiers = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class",
            "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event",
            "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
            "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new",
            "null", "object", "operator", "out", "override", "params", "private", "protected", "public",
            "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static",
            "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong",
            "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        };

        private readonly string _rootNamespace;
        private readonly OpenApiDocument _document;
        private readonly Dictionary<string, string> _schemaNames = new(StringComparer.Ordinal);
        private readonly string _clientName;
        private readonly List<TagGroup> _tagGroups = [];
        private readonly List<SecuritySchemeBinding> _securitySchemes = [];
        private List<SecuritySchemeBinding> _querySecuritySchemes = [];

        private bool _needsFormUrlEncoded;
        private bool _needsMultipartFormData;
        private bool _needsFormatParameter;

        public ClientEmitter(string documentPath, string rootNamespace, OpenApiDocument document)
        {
            _rootNamespace = rootNamespace;
            _document = document;
            _clientName = BuildClientName(documentPath, document);
        }

        public string Emit()
        {
            RegisterSchemaNames();
            RegisterTagGroups();
            RegisterSecuritySchemes();
            _querySecuritySchemes = _securitySchemes.Where(static scheme => scheme.Location == SecuritySchemeLocation.Query).ToList();
            AnalyzeRequiredHelpers();

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using System;");

            if (_needsFormUrlEncoded || _needsMultipartFormData)
            {
                builder.AppendLine("using System.Collections;");
            }

            builder.AppendLine("using System.Collections.Generic;");

            if (_needsFormatParameter)
            {
                builder.AppendLine("using System.Globalization;");
            }

            builder.AppendLine("using System.Net.Http;");
            builder.AppendLine("using System.Net.Http.Json;");
            builder.AppendLine("using System.Text.Json;");
            builder.AppendLine("using System.Text.Json.Serialization;");
            builder.AppendLine("using System.Threading;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine();

            if (!string.IsNullOrWhiteSpace(_rootNamespace))
            {
                builder.Append("namespace ").Append(_rootNamespace).AppendLine(";");
                builder.AppendLine();
            }

            EmitSchemas(builder);

            if (_tagGroups.Count > 0)
            {
                EmitHelperClass(builder);
                builder.AppendLine();
            }

            EmitTagClients(builder);
            EmitClient(builder);
            return builder.ToString();
        }

        private void AnalyzeRequiredHelpers()
        {
            foreach (var tagGroup in _tagGroups)
            {
                foreach (var operation in tagGroup.Operations)
                {
                    var requestBody = ResolveRequestBody(operation.Operation.RequestBody);
                    if (requestBody is not null)
                    {
                        switch (requestBody.Kind)
                        {
                            case RequestBodyKind.FormUrlEncoded:
                                _needsFormUrlEncoded = true;
                                _needsFormatParameter = true;
                                break;
                            case RequestBodyKind.MultipartFormData:
                                _needsMultipartFormData = true;
                                _needsFormatParameter = true;
                                break;
                        }
                    }

                    if (operation.HasParameters)
                    {
                        _needsFormatParameter = true;
                    }
                }
            }

            if (_querySecuritySchemes.Count > 0)
            {
                _needsFormatParameter = true;
            }
        }

        private void RegisterSchemaNames()
        {
            if (_document.Components?.Schemas is null)
            {
                return;
            }

            foreach (var schema in _document.Components.Schemas)
            {
                _schemaNames[schema.Key] = SafeIdentifier(ToPascalCase(schema.Key));
            }
        }

        private void RegisterTagGroups()
        {
            var groups = new Dictionary<string, TagGroup>(StringComparer.Ordinal);

            foreach (var path in _document.Paths)
            {
                foreach (var operation in path.Value.Operations ?? [])
                {
                    var tagName = GetTagName(operation.Value);
                    var groupName = string.IsNullOrWhiteSpace(tagName) ? "Default" : tagName!;
                    var propertyName = SafeIdentifier(ToPascalCase(groupName));
                    var className = propertyName.EndsWith("Client", StringComparison.Ordinal) ? propertyName : propertyName + "Client";

                    if (!groups.TryGetValue(propertyName, out var group))
                    {
                        group = new TagGroup(propertyName, className);
                        groups.Add(propertyName, group);
                    }

                    group.Operations.Add(new OperationGroupItem(path.Key, path.Value, operation.Key.ToString(), operation.Value, CollectParameters(path.Value, operation.Value)));
                }
            }

            _tagGroups.AddRange(groups.Values.OrderBy(static group => group.PropertyName, StringComparer.Ordinal));
        }

        private void RegisterSecuritySchemes()
        {
            if (_document.Components?.SecuritySchemes is null)
            {
                return;
            }

            foreach (var scheme in _document.Components.SecuritySchemes)
            {
                var binding = CreateSecuritySchemeBinding(scheme.Key, scheme.Value);
                if (binding is not null)
                {
                    _securitySchemes.Add(binding);
                }
            }
        }

        private void EmitHelperClass(StringBuilder builder)
        {
            builder.AppendLine("internal static class OpenApiClientHelpers");
            builder.AppendLine("{");
            builder.AppendLine("    internal static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web);");
            builder.AppendLine();
            builder.AppendLine("    internal static string GetSerializedPropertyName(System.Reflection.PropertyInfo property)");
            builder.AppendLine("    {");
            builder.AppendLine("        var attribute = (JsonPropertyNameAttribute?)Attribute.GetCustomAttribute(property, typeof(JsonPropertyNameAttribute));");
            builder.AppendLine("        if (attribute?.Name is { Length: > 0 } name)");
            builder.AppendLine("        {");
            builder.AppendLine("            return name;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        if (property.Name.Length == 1)");
            builder.AppendLine("        {");
            builder.AppendLine("            return char.ToLowerInvariant(property.Name[0]).ToString();");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        return char.ToLowerInvariant(property.Name[0]) + property.Name[1..];");
            builder.AppendLine("    }");

            if (_needsFormatParameter)
            {
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter(object? value)");
                builder.AppendLine("    {");
                builder.AppendLine("        return value switch");
                builder.AppendLine("        {");
                builder.AppendLine("            null => string.Empty,");
                builder.AppendLine("            JsonElement element => element.ToString(),");
                builder.AppendLine("            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),");
                builder.AppendLine("            _ => value.ToString() ?? string.Empty");
                builder.AppendLine("        };");
                builder.AppendLine("    }");
            }

            if (_needsFormUrlEncoded)
            {
                builder.AppendLine();
                builder.AppendLine("    internal static FormUrlEncodedContent CreateFormUrlEncodedContent<TBody>(TBody body)");
                builder.AppendLine("    {");
                builder.AppendLine("        var values = new List<KeyValuePair<string, string>>();");
                builder.AppendLine();
                builder.AppendLine("        foreach (var property in typeof(TBody).GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public))");
                builder.AppendLine("        {");
                builder.AppendLine("            var value = property.GetValue(body);");
                builder.AppendLine("            if (value is null)");
                builder.AppendLine("            {");
                builder.AppendLine("                continue;");
                builder.AppendLine("            }");
                builder.AppendLine();
                builder.AppendLine("            var name = GetSerializedPropertyName(property);");
                builder.AppendLine("            AddFormValues(values, name, value);");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        return new FormUrlEncodedContent(values);");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.AppendLine("    private static void AddFormValues(List<KeyValuePair<string, string>> values, string name, object value)");
                builder.AppendLine("    {");
                builder.AppendLine("        if (value is string or byte[])");
                builder.AppendLine("        {");
                builder.AppendLine("            values.Add(new KeyValuePair<string, string>(name, FormatParameter(value)));");
                builder.AppendLine("            return;");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        if (value is IEnumerable enumerable)");
                builder.AppendLine("        {");
                builder.AppendLine("            foreach (var item in enumerable)");
                builder.AppendLine("            {");
                builder.AppendLine("                if (item is not null)");
                builder.AppendLine("                {");
                builder.AppendLine("                    AddFormValues(values, name, item);");
                builder.AppendLine("                }");
                builder.AppendLine("            }");
                builder.AppendLine();
                builder.AppendLine("            return;");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        values.Add(new KeyValuePair<string, string>(name, FormatParameter(value)));");
                builder.AppendLine("    }");
            }

            if (_needsMultipartFormData)
            {
                builder.AppendLine();
                builder.AppendLine("    internal static MultipartFormDataContent CreateMultipartFormDataContent<TBody>(TBody body)");
                builder.AppendLine("    {");
                builder.AppendLine("        var content = new MultipartFormDataContent();");
                builder.AppendLine();
                builder.AppendLine("        foreach (var property in typeof(TBody).GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public))");
                builder.AppendLine("        {");
                builder.AppendLine("            var value = property.GetValue(body);");
                builder.AppendLine("            if (value is null)");
                builder.AppendLine("            {");
                builder.AppendLine("                continue;");
                builder.AppendLine("            }");
                builder.AppendLine();
                builder.AppendLine("            var name = GetSerializedPropertyName(property);");
                builder.AppendLine("            AddMultipartContent(content, name, value);");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        return content;");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.AppendLine("    private static void AddMultipartContent(MultipartFormDataContent content, string name, object value)");
                builder.AppendLine("    {");
                builder.AppendLine("        switch (value)");
                builder.AppendLine("        {");
                builder.AppendLine("            case byte[] bytes:");
                builder.AppendLine("                content.Add(new ByteArrayContent(bytes), name, name);");
                builder.AppendLine("                return;");
                builder.AppendLine("            case string text:");
                builder.AppendLine("                content.Add(new StringContent(text), name);");
                builder.AppendLine("                return;");
                builder.AppendLine("            case IEnumerable enumerable:");
                builder.AppendLine("                foreach (var item in enumerable)");
                builder.AppendLine("                {");
                builder.AppendLine("                    if (item is not null)");
                builder.AppendLine("                    {");
                builder.AppendLine("                        AddMultipartContent(content, name, item);");
                builder.AppendLine("                    }");
                builder.AppendLine("                }");
                builder.AppendLine("                return;");
                builder.AppendLine("            default:");
                builder.AppendLine("                content.Add(new StringContent(FormatParameter(value)), name);");
                builder.AppendLine("                return;");
                builder.AppendLine("        }");
                builder.AppendLine("    }");
            }

            builder.AppendLine("}");
        }

        private void EmitTagClients(StringBuilder builder)
        {
            foreach (var tagGroup in _tagGroups)
            {
                EmitTagClient(builder, tagGroup);
                builder.AppendLine();
            }
        }

        private void EmitTagClient(StringBuilder builder, TagGroup tagGroup)
        {
            builder.Append("public sealed class ").Append(tagGroup.ClassName).AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    private readonly HttpClient _httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("    private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
            }
            builder.AppendLine();
            var constructorParameters = string.Join(", ",
                new[] { "HttpClient httpClient" }.Concat(
                    _querySecuritySchemes
                        .Select(static scheme => $"string? {scheme.ParameterName}")));
            builder.Append("    internal ").Append(tagGroup.ClassName).Append('(').Append(constructorParameters).AppendLine(")");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient = httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("        ").Append(securityScheme.FieldName).Append(" = ").Append(securityScheme.ParameterName).AppendLine(";");
            }
            builder.AppendLine("    }");

            foreach (var operation in tagGroup.Operations)
            {
                builder.AppendLine();
                EmitOperation(builder, operation.Route, operation.PathItem, operation.OperationType, operation.Operation);
            }

            builder.AppendLine("}");
        }

        private void EmitClient(StringBuilder builder)
        {
            var serverUrl = _document.Servers?.FirstOrDefault()?.Url;
            var constructorParameters = string.Join(", ", _securitySchemes.Select(static scheme => scheme.ParameterDeclaration));

            builder.Append("public partial class ").Append(_clientName).AppendLine(" : IDisposable");
            builder.AppendLine("{");
            builder.AppendLine("    private readonly HttpClient _httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("    private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
            }
            builder.AppendLine();
            builder.Append("    public ").Append(_clientName).Append('(').Append(constructorParameters).AppendLine(")");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient = new HttpClient();");
            if (Uri.TryCreate(serverUrl, UriKind.Absolute, out _))
            {
                builder.Append("        _httpClient.BaseAddress = new Uri(\"").Append(EscapeStringLiteral(serverUrl!)).AppendLine("\", UriKind.Absolute);");
            }

            foreach (var securityScheme in _securitySchemes)
            {
                EmitSecuritySchemeInitialization(builder, securityScheme);
            }

            foreach (var tagGroup in _tagGroups)
            {
                var constructorArguments = string.Join(", ",
                    new[] { "_httpClient" }.Concat(
                        _querySecuritySchemes.Select(static scheme => scheme.FieldName)));
                builder.Append("        ").Append(tagGroup.PropertyName).Append(" = new ").Append(tagGroup.ClassName).Append('(').Append(constructorArguments).AppendLine(");");
            }

            builder.AppendLine("    }");
            builder.AppendLine();

            foreach (var tagGroup in _tagGroups)
            {
                builder.Append("    public ").Append(tagGroup.ClassName).Append(' ').Append(tagGroup.PropertyName).AppendLine(" { get; }");
            }

            if (_tagGroups.Count > 0)
            {
                builder.AppendLine();
            }

            builder.AppendLine("    public void Dispose()");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient.Dispose();");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        private sealed class TagGroup(string propertyName, string className)
        {
            public string PropertyName { get; } = propertyName;
            public string ClassName { get; } = className;
            public List<OperationGroupItem> Operations { get; } = [];
        }

        private sealed class OperationGroupItem(string route, IOpenApiPathItem pathItem, string operationType, OpenApiOperation operation, List<IOpenApiParameter> parameters)
        {
            public string Route { get; } = route;
            public IOpenApiPathItem PathItem { get; } = pathItem;
            public string OperationType { get; } = operationType;
            public OpenApiOperation Operation { get; } = operation;
            public bool HasParameters { get; } = parameters.Count > 0;
        }

        private sealed class SecuritySchemeBinding(string parameterName, string parameterDeclaration, string headerOrParameterName, SecuritySchemeLocation location, bool isBearerToken)
        {
            public string ParameterName { get; } = parameterName;
            public string ParameterDeclaration { get; } = parameterDeclaration;
            public string HeaderOrParameterName { get; } = headerOrParameterName;
            public SecuritySchemeLocation Location { get; } = location;
            public bool IsBearerToken { get; } = isBearerToken;
            public string FieldName { get; } = $"_{parameterName}";
        }

        private enum SecuritySchemeLocation
        {
            Header,
            Query,
            Cookie
        }

        private sealed class RequestBodyInfo(RequestBodyKind kind, string typeName, bool isRequired)
        {
            public RequestBodyKind Kind { get; } = kind;
            public string TypeName { get; } = typeName;
            public bool IsRequired { get; } = isRequired;
        }

        private sealed class ResponseInfo(ResponseKind kind, string typeName)
        {
            public ResponseKind Kind { get; } = kind;
            public string TypeName { get; } = typeName;
        }

        private enum RequestBodyKind
        {
            Json,
            FormUrlEncoded,
            MultipartFormData
        }

        private enum ResponseKind
        {
            None,
            Json,
            String,
            Binary
        }

        private sealed class SchemaPropertyInfo(string name, IOpenApiSchema schema, bool required)
        {
            public string Name { get; } = name;
            public IOpenApiSchema Schema { get; } = schema;
            public bool Required { get; } = required;
        }
    }
}
