using System.Text;

namespace OpenApiWeaver;

public sealed partial class ClientGenerator
{
    private static class SupportTypesEmitter
    {
        public static string Emit(string rootNamespace)
        {
            var builder = new StringBuilder();
            var writer = new IndentedStringBuilder(builder);
            writer.AppendLine("// <auto-generated />");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("using System;");
            writer.AppendLine("using System.Collections.Generic;");
            writer.AppendLine("using System.Globalization;");
            writer.AppendLine("using System.Text;");
            writer.AppendLine("using System.Text.Json;");
            writer.AppendLine();

            if (!string.IsNullOrWhiteSpace(rootNamespace))
            {
                writer.Append("namespace ").Append(rootNamespace).AppendLine(";");
                writer.AppendLine();
            }

            EmitExceptionTypes(writer);
            writer.AppendLine();
            EmitHelperClass(writer);
            return builder.ToString();
        }

        private static void EmitExceptionTypes(IndentedStringBuilder writer)
        {
            writer.AppendLine("public class OpenApiException : Exception");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("public OpenApiException(int statusCode, string? reasonPhrase, string? contentType, string? responseContent, Exception? innerException = null)");
                writer.AppendLine(": base(CreateMessage(statusCode, reasonPhrase), innerException)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("StatusCode = statusCode;");
                    writer.AppendLine("ReasonPhrase = reasonPhrase;");
                    writer.AppendLine("ContentType = contentType;");
                    writer.AppendLine("ResponseContent = responseContent;");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("public int StatusCode { get; }");
                writer.AppendLine();
                writer.AppendLine("public string? ReasonPhrase { get; }");
                writer.AppendLine();
                writer.AppendLine("public string? ContentType { get; }");
                writer.AppendLine();
                writer.AppendLine("public string? ResponseContent { get; }");
                writer.AppendLine();
                writer.AppendLine("private static string CreateMessage(int statusCode, string? reasonPhrase)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return string.IsNullOrWhiteSpace(reasonPhrase)");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("? $\"The HTTP request failed with status code {statusCode}.\"");
                        writer.AppendLine(": $\"The HTTP request failed with status code {statusCode} ({reasonPhrase}).\";");
                    }
                }

                writer.AppendLine("}");
            }

            writer.AppendLine("}");
            writer.AppendLine();
            writer.AppendLine("public class OpenApiException<TError> : OpenApiException");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("public OpenApiException(int statusCode, string? reasonPhrase, string? contentType, string? responseContent, TError? error, Exception? innerException = null)");
                writer.AppendLine(": base(statusCode, reasonPhrase, contentType, responseContent, innerException)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("Error = error;");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("public TError? Error { get; }");
            }

            writer.AppendLine("}");
        }

        private static void EmitHelperClass(IndentedStringBuilder writer)
        {
            writer.AppendLine("internal static class OpenApiClientHelpers");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("internal static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web);");
                writer.AppendLine();
                writer.AppendLine("internal static string FormatParameter(string? value) => value ?? string.Empty;");
                writer.AppendLine();
                writer.AppendLine("internal static string FormatParameter(JsonElement value) => value.ToString();");
                writer.AppendLine();
                writer.AppendLine("internal static string FormatParameter(bool value) => value ? \"true\" : \"false\";");
                writer.AppendLine();
                writer.AppendLine("internal static string FormatParameter(bool? value) => value is bool actual ? (actual ? \"true\" : \"false\") : string.Empty;");
                writer.AppendLine();
                writer.AppendLine("internal static string FormatParameter<T>(T value) where T : struct, IFormattable");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return FormatFormattable(value);");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static string FormatParameter<T>(T? value) where T : struct, IFormattable");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return value is T actual ? FormatFormattable(actual) : string.Empty;");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static string FormatParameter(object? value)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return value switch");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("null => string.Empty,");
                        writer.AppendLine("bool boolean => boolean ? \"true\" : \"false\",");
                        writer.AppendLine("DateTimeOffset dateTimeOffset => dateTimeOffset.ToString(\"o\", CultureInfo.InvariantCulture),");
                        writer.AppendLine("DateTime dateTime => dateTime.ToString(\"o\", CultureInfo.InvariantCulture),");
                        writer.AppendLine("DateOnly dateOnly => dateOnly.ToString(\"yyyy-MM-dd\", CultureInfo.InvariantCulture),");
                        writer.AppendLine("TimeOnly timeOnly => timeOnly.ToString(\"HH:mm:ss.FFFFFFF\", CultureInfo.InvariantCulture),");
                        writer.AppendLine("IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),");
                        writer.AppendLine("_ => value.ToString() ?? string.Empty");
                    }

                    writer.AppendLine("};");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("private static string FormatFormattable<T>(T value) where T : struct, IFormattable");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return value switch");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("DateTimeOffset dateTimeOffset => dateTimeOffset.ToString(\"o\", CultureInfo.InvariantCulture),");
                        writer.AppendLine("DateTime dateTime => dateTime.ToString(\"o\", CultureInfo.InvariantCulture),");
                        writer.AppendLine("DateOnly dateOnly => dateOnly.ToString(\"yyyy-MM-dd\", CultureInfo.InvariantCulture),");
                        writer.AppendLine("TimeOnly timeOnly => timeOnly.ToString(\"HH:mm:ss.FFFFFFF\", CultureInfo.InvariantCulture),");
                        writer.AppendLine("_ => value.ToString(null, CultureInfo.InvariantCulture)");
                    }

                    writer.AppendLine("};");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static void AppendQueryParameter(StringBuilder builder, ref bool hasQuery, string name, string value)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("builder.Append(hasQuery ? '&' : '?');");
                    writer.AppendLine("hasQuery = true;");
                    writer.AppendLine("builder.Append(name);");
                    writer.AppendLine("builder.Append('=');");
                    writer.AppendLine("builder.Append(Uri.EscapeDataString(value));");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static void AppendQueryParameters<T>(StringBuilder builder, ref bool hasQuery, string name, IEnumerable<T> values)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("foreach (var value in values)");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("AppendQueryParameter(builder, ref hasQuery, name, FormatParameter(value));");
                    }

                    writer.AppendLine("}");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static string FormatCollectionParameter<T>(IEnumerable<T>? values)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("if (values is null)");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("return string.Empty;");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("var builder = new StringBuilder();");
                    writer.AppendLine("foreach (var value in values)");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("if (builder.Length > 0)");
                        writer.AppendLine("{");
                        using (writer.PushIndent())
                        {
                            writer.AppendLine("builder.Append(',');");
                        }

                        writer.AppendLine("}");
                        writer.AppendLine();
                        writer.AppendLine("builder.Append(FormatParameter(value));");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("return builder.ToString();");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static void AppendCookieParameter(StringBuilder builder, string name, string value)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("if (builder.Length > 0)");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("builder.Append(\"; \");");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("builder.Append(name);");
                    writer.AppendLine("builder.Append('=');");
                    writer.AppendLine("builder.Append(Uri.EscapeDataString(value));");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static bool HasJsonContentType(string? contentType)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return !string.IsNullOrWhiteSpace(contentType) && contentType.Contains(\"json\", StringComparison.OrdinalIgnoreCase);");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static bool ResponseMatchesStatusCode(int statusCode, string statusCodePattern)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("if (string.Equals(statusCodePattern, \"default\", StringComparison.OrdinalIgnoreCase))");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("return true;");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("if (statusCodePattern.Length == 3");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("&& char.IsDigit(statusCodePattern[0])");
                        writer.AppendLine("&& statusCodePattern[1] is 'X' or 'x'");
                        writer.AppendLine("&& statusCodePattern[2] is 'X' or 'x')");
                    }

                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("var prefix = statusCodePattern[0] - '0';");
                        writer.AppendLine("return statusCode >= prefix * 100 && statusCode < (prefix + 1) * 100;");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("return int.TryParse(statusCodePattern, out var expectedStatusCode) && statusCode == expectedStatusCode;");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static T? DeserializeResponseContent<T>(string? responseContent)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return DeserializeResponseContent<T>(responseContent, SerializerOptions);");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static T? DeserializeResponseContent<T>(string? responseContent, JsonSerializerOptions options)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return string.IsNullOrWhiteSpace(responseContent)");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("? default");
                        writer.AppendLine(": JsonSerializer.Deserialize<T>(responseContent, options);");
                    }
                }

                writer.AppendLine("}");
            }

            writer.AppendLine("}");
        }
    }
}
