using System.Text;

namespace OpenApiWeaver;

public sealed partial class ClientGenerator
{
    private sealed partial class Emitter(ClientModel model)
    {
        public string Emit()
        {
            var builder = new StringBuilder();
            var writer = new IndentedStringBuilder(builder);
            writer.AppendLine("// <auto-generated />");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("using System;");
            writer.AppendLine("using System.Collections.Generic;");
            writer.AppendLine("using System.Net.Http;");
            writer.AppendLine("using System.Net.Http.Json;");
            writer.AppendLine("using System.Text;");
            writer.AppendLine("using System.Text.Json;");
            writer.AppendLine("using System.Text.Json.Serialization;");
            writer.AppendLine("using System.Threading;");
            writer.AppendLine("using System.Threading.Tasks;");
            writer.AppendLine();

            if (!string.IsNullOrWhiteSpace(model.RootNamespace))
            {
                writer.Append("namespace ").Append(model.RootNamespace).AppendLine(";");
                writer.AppendLine();
            }

            EmitSchemas(writer);
            if (model.HasDirectionalSchemaProperties)
            {
                EmitJsonSerializerOptions(writer);
                writer.AppendLine();
            }

            EmitTagClients(writer);
            EmitClient(writer);
            return builder.ToString();
        }

        private static string NormalizeBaseAddress(string serverUrl)
        {
            var builder = new UriBuilder(new Uri(serverUrl, UriKind.Absolute));
            if (builder.Path.Length == 0)
            {
                builder.Path = "/";
            }
            else if (!builder.Path.EndsWith("/", StringComparison.Ordinal))
            {
                builder.Path += "/";
            }

            return builder.Uri.AbsoluteUri;
        }

        private void EmitTagClients(IndentedStringBuilder writer)
        {
            foreach (var tagGroup in model.TagGroups)
            {
                EmitTagClient(writer, tagGroup);
                writer.AppendLine();
            }
        }

        private void EmitTagClient(IndentedStringBuilder writer, TagGroup tagGroup)
        {
            EmitDocComment(
                writer,
                summary: $"{tagGroup.PropertyName} operations.",
                remarks: tagGroup.Description);
            writer.Append("public sealed class ").Append(tagGroup.ClassName).AppendLine();
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("private readonly HttpClient _httpClient;");
                foreach (var securityScheme in model.SecuritySchemes)
                {
                    writer.Append("private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
                }

                writer.AppendLine();
                var constructorParameters = string.Join(", ",
                    new[] { "HttpClient httpClient" }.Concat(
                        model.SecuritySchemes
                            .Select(static scheme => $"string? {scheme.ParameterName}")));
                writer.Append("internal ").Append(tagGroup.ClassName).Append('(').Append(constructorParameters).AppendLine(")");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("_httpClient = httpClient;");
                    foreach (var securityScheme in model.SecuritySchemes)
                    {
                        writer.Append(securityScheme.FieldName).Append(" = ").Append(securityScheme.ParameterName).AppendLine(";");
                    }
                }

                writer.AppendLine("}");

                foreach (var operation in tagGroup.Operations)
                {
                    writer.AppendLine();
                    EmitOperation(writer, operation);
                }
            }

            writer.AppendLine("}");
        }

        private void EmitClient(IndentedStringBuilder writer)
        {
            var constructorParameters = string.Join(", ", model.SecuritySchemes.Select(static scheme => scheme.ParameterDeclaration));
            var injectedConstructorParameters = string.Join(", ", new[] { "HttpClient httpClient" }.Concat(model.SecuritySchemes.Select(static scheme => scheme.ParameterDeclaration)));
            var privateConstructorParameters = string.Join(", ", new[] { "HttpClient httpClient", "bool ownsHttpClient" }.Concat(model.SecuritySchemes.Select(static scheme => scheme.ParameterDeclaration)));
            var ownedConstructorArguments = string.Join(", ", new[] { "new HttpClient()", "true" }.Concat(model.SecuritySchemes.Select(static scheme => scheme.ParameterName)));
            var injectedConstructorArguments = string.Join(", ", new[] { "httpClient", "false" }.Concat(model.SecuritySchemes.Select(static scheme => scheme.ParameterName)));

            EmitDocComment(
                writer,
                summary: model.Summary,
                remarks: model.Description);
            writer.Append("public partial class ").Append(model.ClientName).AppendLine(" : IDisposable");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("private readonly HttpClient _httpClient;");
                writer.AppendLine("private readonly bool _ownsHttpClient;");
                foreach (var securityScheme in model.SecuritySchemes)
                {
                    writer.Append("private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
                }

                writer.AppendLine();
                writer.Append("public ").Append(model.ClientName).Append('(').Append(constructorParameters).AppendLine(")");
                writer.Append("    : this(").Append(ownedConstructorArguments).AppendLine(")");
                writer.AppendLine("{");
                writer.AppendLine("}");
                writer.AppendLine();

                writer.Append("public ").Append(model.ClientName).Append('(').Append(injectedConstructorParameters).AppendLine(")");
                writer.Append("    : this(").Append(injectedConstructorArguments).AppendLine(")");
                writer.AppendLine("{");
                writer.AppendLine("}");
                writer.AppendLine();

                writer.Append("private ").Append(model.ClientName).Append('(').Append(privateConstructorParameters).AppendLine(")");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("_httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));");
                    writer.AppendLine("_ownsHttpClient = ownsHttpClient;");
                    if (Uri.TryCreate(model.ServerUrl, UriKind.Absolute, out _))
                    {
                        writer.AppendLine("if (_httpClient.BaseAddress is null)");
                        writer.AppendLine("{");
                        using (writer.PushIndent())
                        {
                            writer.Append("_httpClient.BaseAddress = new Uri(\"").Append(EscapeStringLiteral(NormalizeBaseAddress(model.ServerUrl!))).AppendLine("\", UriKind.Absolute);");
                        }

                        writer.AppendLine("}");
                    }

                    foreach (var securityScheme in model.SecuritySchemes)
                    {
                        writer.Append(securityScheme.FieldName).Append(" = ").Append(securityScheme.ParameterName).AppendLine(";");
                    }

                    var constructorArguments = string.Join(", ",
                        new[] { "_httpClient" }.Concat(
                            model.SecuritySchemes.Select(static scheme => scheme.FieldName)));
                    foreach (var tagGroup in model.TagGroups)
                    {
                        writer.Append(tagGroup.PropertyName).Append(" = new ").Append(tagGroup.ClassName).Append('(').Append(constructorArguments).AppendLine(");");
                    }
                }

                writer.AppendLine("}");
                writer.AppendLine();

                foreach (var tagGroup in model.TagGroups)
                {
                    EmitDocComment(
                        writer,
                        summary: $"{tagGroup.PropertyName} operations.",
                        remarks: tagGroup.Description);
                    writer.Append("public ").Append(tagGroup.ClassName).Append(' ').Append(tagGroup.PropertyName).AppendLine(" { get; }");
                }

                if (model.TagGroups.Count > 0)
                {
                    writer.AppendLine();
                }

                writer.AppendLine("public void Dispose()");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("if (_ownsHttpClient)");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("_httpClient.Dispose();");
                    }

                    writer.AppendLine("}");
                }

                writer.AppendLine("}");
            }

            writer.AppendLine("}");
        }
    }
}
