using System.Text;

using Microsoft.OpenApi;

namespace OpenApiWeaver;

public sealed partial class OpenApiWeaverSourceGenerator
{
    private sealed partial class ClientEmitter
    {
        private static readonly HashSet<string> s_reservedIdentifiers = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class",
            "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event",
            "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
            "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new",
            "null", "object", "operator", "out", "override", "params", "private", "protected", "public",
            "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static",
            "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong",
            "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        };

        private readonly string _rootNamespace;
        private readonly OpenApiDocument _document;
        private readonly Dictionary<string, string> _schemaNames = new(StringComparer.Ordinal);
        private readonly string _clientName;
        private readonly List<TagGroup> _tagGroups = [];
        private readonly Dictionary<string, string> _tagDescriptions = new(StringComparer.Ordinal);
        private readonly List<SecuritySchemeBinding> _securitySchemes = [];
        private List<SecuritySchemeBinding> _querySecuritySchemes = null!;

        private bool _needsFormUrlEncoded;
        private bool _needsMultipartFormData;
        private bool _needsFormatParameter;

        public ClientEmitter(string documentPath, string rootNamespace, OpenApiDocument document)
        {
            _rootNamespace = rootNamespace;
            _document = document;
            _clientName = BuildClientName(documentPath, document);
        }

        public string Emit()
        {
            RegisterSchemaNames();
            RegisterTagGroups();
            RegisterSecuritySchemes();
            _querySecuritySchemes = _securitySchemes.Where(static scheme => scheme.Location == SecuritySchemeLocation.Query).ToList();
            AnalyzeRequiredHelpers();

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using System;");

            builder.AppendLine("using System.Collections.Generic;");

            if (_needsFormatParameter)
            {
                builder.AppendLine("using System.Globalization;");
            }

            builder.AppendLine("using System.Net.Http;");
            builder.AppendLine("using System.Net.Http.Json;");
            builder.AppendLine("using System.Text;");
            builder.AppendLine("using System.Text.Json;");
            builder.AppendLine("using System.Text.Json.Serialization;");
            builder.AppendLine("using System.Threading;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine();

            if (!string.IsNullOrWhiteSpace(_rootNamespace))
            {
                builder.Append("namespace ").Append(_rootNamespace).AppendLine(";");
                builder.AppendLine();
            }

            EmitSchemas(builder);

            if (_tagGroups.Count > 0)
            {
                EmitHelperClass(builder);
                builder.AppendLine();
            }

            EmitTagClients(builder);
            EmitClient(builder);
            return builder.ToString();
        }

        private void AnalyzeRequiredHelpers()
        {
            if (_querySecuritySchemes.Count > 0)
            {
                _needsFormatParameter = true;
            }

            foreach (var tagGroup in _tagGroups)
            {
                if (_needsFormUrlEncoded && _needsMultipartFormData && _needsFormatParameter)
                {
                    break;
                }

                foreach (var operation in tagGroup.Operations)
                {
                    if (_needsFormUrlEncoded && _needsMultipartFormData && _needsFormatParameter)
                    {
                        break;
                    }

                    var requestBody = ResolveRequestBody(operation.Operation.RequestBody);
                    if (requestBody is not null)
                    {
                        switch (requestBody.Kind)
                        {
                            case RequestBodyKind.FormUrlEncoded:
                                _needsFormUrlEncoded = true;
                                _needsFormatParameter = true;
                                break;
                            case RequestBodyKind.MultipartFormData:
                                _needsMultipartFormData = true;
                                _needsFormatParameter = true;
                                break;
                        }
                    }

                    if (operation.HasParameters)
                    {
                        _needsFormatParameter = true;
                    }
                }
            }
        }

        private void RegisterSchemaNames()
        {
            if (_document.Components?.Schemas is null)
            {
                return;
            }

            foreach (var schema in _document.Components.Schemas)
            {
                _schemaNames[schema.Key] = SafeIdentifier(ToPascalCase(schema.Key));
            }
        }

        private void RegisterTagGroups()
        {
            if (_document.Tags is not null)
            {
                foreach (var tag in _document.Tags)
                {
                    var tagName = tag.Name;
                    if (!string.IsNullOrWhiteSpace(tagName) && !string.IsNullOrWhiteSpace(tag.Description))
                    {
                        _tagDescriptions[tagName!] = tag.Description!;
                    }
                }
            }

            var groups = new Dictionary<string, TagGroup>(StringComparer.Ordinal);

            foreach (var path in _document.Paths)
            {
                foreach (var operation in path.Value.Operations ?? [])
                {
                    var tagName = GetTagName(operation.Value);
                    var groupName = string.IsNullOrWhiteSpace(tagName) ? "Default" : tagName!;
                    var propertyName = SafeIdentifier(ToPascalCase(groupName));
                    var className = propertyName.EndsWith("Client", StringComparison.Ordinal) ? propertyName : propertyName + "Client";

                    if (!groups.TryGetValue(propertyName, out var group))
                    {
                        _tagDescriptions.TryGetValue(groupName, out var tagDescription);
                        group = new TagGroup(propertyName, className, tagDescription);
                        groups.Add(propertyName, group);
                    }

                    group.Operations.Add(new OperationGroupItem(path.Key, operation.Key.ToString(), operation.Value, CollectParameters(path.Value, operation.Value)));
                }
            }

            _tagGroups.AddRange(groups.Values.OrderBy(static group => group.PropertyName, StringComparer.Ordinal));
        }

        private void RegisterSecuritySchemes()
        {
            if (_document.Components?.SecuritySchemes is null)
            {
                return;
            }

            foreach (var scheme in _document.Components.SecuritySchemes)
            {
                var binding = CreateSecuritySchemeBinding(scheme.Key, scheme.Value);
                if (binding is not null)
                {
                    _securitySchemes.Add(binding);
                }
            }
        }

        private void EmitHelperClass(StringBuilder builder)
        {
            builder.AppendLine("internal static class OpenApiClientHelpers");
            builder.AppendLine("{");
            builder.AppendLine("    internal static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web);");

            if (_needsFormatParameter)
            {
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter(string? value) => value ?? string.Empty;");
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter(JsonElement value) => value.ToString();");
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter<T>(T value) where T : struct, IFormattable");
                builder.AppendLine("    {");
                builder.AppendLine("        return value.ToString(null, CultureInfo.InvariantCulture);");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter<T>(T? value) where T : struct, IFormattable");
                builder.AppendLine("    {");
                builder.AppendLine("        return value?.ToString(null, CultureInfo.InvariantCulture) ?? string.Empty;");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter(object? value)");
                builder.AppendLine("    {");
                builder.AppendLine("        return value switch");
                builder.AppendLine("        {");
                builder.AppendLine("            null => string.Empty,");
                builder.AppendLine("            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),");
                builder.AppendLine("            _ => value.ToString() ?? string.Empty");
                builder.AppendLine("        };");
                builder.AppendLine("    }");
            }

            builder.AppendLine();
            builder.AppendLine("    internal static void AppendQueryParameter(StringBuilder builder, ref bool hasQuery, string name, string value)");
            builder.AppendLine("    {");
            builder.AppendLine("        builder.Append(hasQuery ? '&' : '?');");
            builder.AppendLine("        hasQuery = true;");
            builder.AppendLine("        builder.Append(name);");
            builder.AppendLine("        builder.Append('=');");
            builder.AppendLine("        builder.Append(Uri.EscapeDataString(value));");
            builder.AppendLine("    }");

            builder.AppendLine("}");
        }

        private void EmitTagClients(StringBuilder builder)
        {
            foreach (var tagGroup in _tagGroups)
            {
                EmitTagClient(builder, tagGroup);
                builder.AppendLine();
            }
        }

        private void EmitTagClient(StringBuilder builder, TagGroup tagGroup)
        {
            EmitDocComment(
                builder,
                "    ",
                summary: $"{tagGroup.PropertyName} operations.",
                remarks: tagGroup.Description);
            builder.Append("public sealed class ").Append(tagGroup.ClassName).AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    private readonly HttpClient _httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("    private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
            }
            builder.AppendLine();
            var constructorParameters = string.Join(", ",
                new[] { "HttpClient httpClient" }.Concat(
                    _querySecuritySchemes
                        .Select(static scheme => $"string? {scheme.ParameterName}")));
            builder.Append("    internal ").Append(tagGroup.ClassName).Append('(').Append(constructorParameters).AppendLine(")");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient = httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("        ").Append(securityScheme.FieldName).Append(" = ").Append(securityScheme.ParameterName).AppendLine(";");
            }
            builder.AppendLine("    }");

            foreach (var operation in tagGroup.Operations)
            {
                builder.AppendLine();
                EmitOperation(builder, operation.Route, operation.OperationType, operation.Operation, operation.Parameters);
            }

            builder.AppendLine("}");
        }

        private void EmitClient(StringBuilder builder)
        {
            var serverUrl = _document.Servers?.FirstOrDefault()?.Url;
            var constructorParameters = string.Join(", ", _securitySchemes.Select(static scheme => scheme.ParameterDeclaration));

            EmitDocComment(
                builder,
                "    ",
                summary: !string.IsNullOrWhiteSpace(_document.Info.Title) ? _document.Info.Title : _clientName,
                remarks: _document.Info.Description);
            builder.Append("public partial class ").Append(_clientName).AppendLine(" : IDisposable");
            builder.AppendLine("{");
            builder.AppendLine("    private readonly HttpClient _httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("    private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
            }
            builder.AppendLine();
            builder.Append("    public ").Append(_clientName).Append('(').Append(constructorParameters).AppendLine(")");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient = new HttpClient();");
            if (Uri.TryCreate(serverUrl, UriKind.Absolute, out _))
            {
                builder.Append("        _httpClient.BaseAddress = new Uri(\"").Append(EscapeStringLiteral(serverUrl!)).AppendLine("\", UriKind.Absolute);");
            }

            foreach (var securityScheme in _securitySchemes)
            {
                EmitSecuritySchemeInitialization(builder, securityScheme);
            }

            var constructorArguments = string.Join(", ",
                new[] { "_httpClient" }.Concat(
                    _querySecuritySchemes.Select(static scheme => scheme.FieldName)));
            foreach (var tagGroup in _tagGroups)
            {
                builder.Append("        ").Append(tagGroup.PropertyName).Append(" = new ").Append(tagGroup.ClassName).Append('(').Append(constructorArguments).AppendLine(");");
            }

            builder.AppendLine("    }");
            builder.AppendLine();

            foreach (var tagGroup in _tagGroups)
            {
                EmitDocComment(
                    builder,
                    "        ",
                    summary: $"{tagGroup.PropertyName} operations.",
                    remarks: tagGroup.Description);
                builder.Append("    public ").Append(tagGroup.ClassName).Append(' ').Append(tagGroup.PropertyName).AppendLine(" { get; }");
            }

            if (_tagGroups.Count > 0)
            {
                builder.AppendLine();
            }

            builder.AppendLine("    public void Dispose()");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient.Dispose();");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        private sealed class TagGroup(string propertyName, string className, string? description)
        {
            public string PropertyName { get; } = propertyName;
            public string ClassName { get; } = className;
            public string? Description { get; } = description;
            public List<OperationGroupItem> Operations { get; } = [];
        }

        private sealed class OperationGroupItem(string route, string operationType, OpenApiOperation operation, List<IOpenApiParameter> parameters)
        {
            public string Route { get; } = route;
            public string OperationType { get; } = operationType;
            public OpenApiOperation Operation { get; } = operation;
            public List<IOpenApiParameter> Parameters { get; } = parameters;
            public bool HasParameters { get; } = parameters.Count > 0;
        }

        private sealed class SecuritySchemeBinding(string parameterName, string parameterDeclaration, string headerOrParameterName, SecuritySchemeLocation location, bool isBearerToken)
        {
            public string ParameterName { get; } = parameterName;
            public string ParameterDeclaration { get; } = parameterDeclaration;
            public string HeaderOrParameterName { get; } = headerOrParameterName;
            public SecuritySchemeLocation Location { get; } = location;
            public bool IsBearerToken { get; } = isBearerToken;
            public string FieldName { get; } = $"_{parameterName}";
        }

        private enum SecuritySchemeLocation
        {
            Header,
            Query,
            Cookie
        }

        private sealed class RequestBodyInfo(RequestBodyKind kind, string typeName, bool isRequired, IOpenApiSchema? schema)
        {
            public RequestBodyKind Kind { get; } = kind;
            public string TypeName { get; } = typeName;
            public bool IsRequired { get; } = isRequired;
            public IOpenApiSchema? Schema { get; } = schema;
        }

        private sealed class ResponseInfo(ResponseKind kind, string typeName)
        {
            public ResponseKind Kind { get; } = kind;
            public string TypeName { get; } = typeName;
        }

        private enum RequestBodyKind
        {
            Json,
            FormUrlEncoded,
            MultipartFormData
        }

        private enum ResponseKind
        {
            None,
            Json,
            String,
            Binary
        }

        private sealed class SchemaPropertyInfo(string name, IOpenApiSchema schema, bool required)
        {
            public string Name { get; } = name;
            public IOpenApiSchema Schema { get; } = schema;
            public bool Required { get; } = required;
        }

        private enum RequestBodyValueKind
        {
            Scalar,
            Binary,
            Collection
        }

        private sealed class RequestBodyPropertyInfo(string serializedName, string propertyName, RequestBodyValueKind kind, bool nullable, RequestBodyValueKind? elementKind = null, bool elementNullable = false)
        {
            public string SerializedName { get; } = serializedName;
            public string PropertyName { get; } = propertyName;
            public RequestBodyValueKind Kind { get; } = kind;
            public bool Nullable { get; } = nullable;
            public RequestBodyValueKind? ElementKind { get; } = elementKind;
            public bool ElementNullable { get; } = elementNullable;
        }
    }
}
