using System.Text;

namespace OpenApiWeaver;

public sealed partial class OpenApiWeaverSourceGenerator
{
    private sealed partial class ClientEmitter(ClientModel model)
    {
        private List<SecuritySchemeBinding> _querySecuritySchemes = null!;

        private bool _needsFormUrlEncoded;
        private bool _needsMultipartFormData;
        private bool _needsFormatParameter;

        public string Emit()
        {
            _querySecuritySchemes = model.SecuritySchemes.Where(static scheme => scheme.Location == SecuritySchemeLocation.Query).ToList();
            AnalyzeRequiredHelpers();

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using System;");

            builder.AppendLine("using System.Collections.Generic;");

            if (_needsFormatParameter)
            {
                builder.AppendLine("using System.Globalization;");
            }

            builder.AppendLine("using System.Net.Http;");
            builder.AppendLine("using System.Net.Http.Json;");
            builder.AppendLine("using System.Text;");
            builder.AppendLine("using System.Text.Json;");
            builder.AppendLine("using System.Text.Json.Serialization;");
            builder.AppendLine("using System.Threading;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine();

            if (!string.IsNullOrWhiteSpace(model.RootNamespace))
            {
                builder.Append("namespace ").Append(model.RootNamespace).AppendLine(";");
                builder.AppendLine();
            }

            EmitSchemas(builder);

            if (model.TagGroups.Count > 0)
            {
                EmitSupportTypes(builder);
                builder.AppendLine();
            }

            EmitTagClients(builder);
            EmitClient(builder);
            return builder.ToString();
        }

        private void AnalyzeRequiredHelpers()
        {
            if (_querySecuritySchemes.Count > 0)
            {
                _needsFormatParameter = true;
            }

            foreach (var tagGroup in model.TagGroups)
            {
                if (_needsFormUrlEncoded && _needsMultipartFormData && _needsFormatParameter)
                {
                    break;
                }

                foreach (var operation in tagGroup.Operations)
                {
                    if (_needsFormUrlEncoded && _needsMultipartFormData && _needsFormatParameter)
                    {
                        break;
                    }

                    var requestBody = operation.RequestBody;
                    if (requestBody is not null)
                    {
                        switch (requestBody.Kind)
                        {
                            case RequestBodyKind.FormUrlEncoded:
                                _needsFormUrlEncoded = true;
                                _needsFormatParameter = true;
                                break;
                            case RequestBodyKind.MultipartFormData:
                                _needsMultipartFormData = true;
                                _needsFormatParameter = true;
                                break;
                        }
                    }

                    if (operation.HasParameters)
                    {
                        _needsFormatParameter = true;
                    }
                }
            }
        }

        private static string NormalizeBaseAddress(string serverUrl)
        {
            var builder = new UriBuilder(new Uri(serverUrl, UriKind.Absolute));
            if (builder.Path.Length == 0)
            {
                builder.Path = "/";
            }
            else if (!builder.Path.EndsWith("/", StringComparison.Ordinal))
            {
                builder.Path += "/";
            }

            return builder.Uri.AbsoluteUri;
        }

        private void EmitSupportTypes(StringBuilder builder)
        {
            EmitExceptionTypes(builder);
            builder.AppendLine();

            EmitHelperClass(builder);
        }

        private static void EmitExceptionTypes(StringBuilder builder)
        {
            builder.AppendLine("public class OpenApiException : Exception");
            builder.AppendLine("{");
            builder.AppendLine("    public OpenApiException(int statusCode, string? reasonPhrase, string? contentType, string? responseContent, Exception? innerException = null)");
            builder.AppendLine("        : base(CreateMessage(statusCode, reasonPhrase), innerException)");
            builder.AppendLine("    {");
            builder.AppendLine("        StatusCode = statusCode;");
            builder.AppendLine("        ReasonPhrase = reasonPhrase;");
            builder.AppendLine("        ContentType = contentType;");
            builder.AppendLine("        ResponseContent = responseContent;");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public int StatusCode { get; }");
            builder.AppendLine();
            builder.AppendLine("    public string? ReasonPhrase { get; }");
            builder.AppendLine();
            builder.AppendLine("    public string? ContentType { get; }");
            builder.AppendLine();
            builder.AppendLine("    public string? ResponseContent { get; }");
            builder.AppendLine();
            builder.AppendLine("    private static string CreateMessage(int statusCode, string? reasonPhrase)");
            builder.AppendLine("    {");
            builder.AppendLine("        return string.IsNullOrWhiteSpace(reasonPhrase)");
            builder.AppendLine("            ? $\"The HTTP request failed with status code {statusCode}.\"");
            builder.AppendLine("            : $\"The HTTP request failed with status code {statusCode} ({reasonPhrase}).\";");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
            builder.AppendLine("public class OpenApiException<TError> : OpenApiException");
            builder.AppendLine("{");
            builder.AppendLine("    public OpenApiException(int statusCode, string? reasonPhrase, string? contentType, string? responseContent, TError? error, Exception? innerException = null)");
            builder.AppendLine("        : base(statusCode, reasonPhrase, contentType, responseContent, innerException)");
            builder.AppendLine("    {");
            builder.AppendLine("        Error = error;");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public TError? Error { get; }");
            builder.AppendLine("}");
        }

        private void EmitHelperClass(StringBuilder builder)
        {
            builder.AppendLine("internal static class OpenApiClientHelpers");
            builder.AppendLine("{");
            builder.AppendLine("    internal static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web);");

            if (_needsFormatParameter)
            {
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter(string? value) => value ?? string.Empty;");
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter(JsonElement value) => value.ToString();");
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter<T>(T value) where T : struct, IFormattable");
                builder.AppendLine("    {");
                builder.AppendLine("        return value.ToString(null, CultureInfo.InvariantCulture);");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter<T>(T? value) where T : struct, IFormattable");
                builder.AppendLine("    {");
                builder.AppendLine("        return value?.ToString(null, CultureInfo.InvariantCulture) ?? string.Empty;");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.AppendLine("    internal static string FormatParameter(object? value)");
                builder.AppendLine("    {");
                builder.AppendLine("        return value switch");
                builder.AppendLine("        {");
                builder.AppendLine("            null => string.Empty,");
                builder.AppendLine("            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),");
                builder.AppendLine("            _ => value.ToString() ?? string.Empty");
                builder.AppendLine("        };");
                builder.AppendLine("    }");
            }

            builder.AppendLine();
            builder.AppendLine("    internal static void AppendQueryParameter(StringBuilder builder, ref bool hasQuery, string name, string value)");
            builder.AppendLine("    {");
            builder.AppendLine("        builder.Append(hasQuery ? '&' : '?');");
            builder.AppendLine("        hasQuery = true;");
            builder.AppendLine("        builder.Append(name);");
            builder.AppendLine("        builder.Append('=');");
            builder.AppendLine("        builder.Append(Uri.EscapeDataString(value));");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    internal static bool HasJsonContentType(string? contentType)");
            builder.AppendLine("    {");
            builder.AppendLine("        return !string.IsNullOrWhiteSpace(contentType) && contentType.Contains(\"json\", StringComparison.OrdinalIgnoreCase);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    internal static bool ResponseMatchesStatusCode(int statusCode, string statusCodePattern)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (string.Equals(statusCodePattern, \"default\", StringComparison.OrdinalIgnoreCase))");
            builder.AppendLine("        {");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        if (statusCodePattern.Length == 3");
            builder.AppendLine("            && char.IsDigit(statusCodePattern[0])");
            builder.AppendLine("            && statusCodePattern[1] is 'X' or 'x'");
            builder.AppendLine("            && statusCodePattern[2] is 'X' or 'x')");
            builder.AppendLine("        {");
            builder.AppendLine("            var prefix = statusCodePattern[0] - '0';");
            builder.AppendLine("            return statusCode >= prefix * 100 && statusCode < (prefix + 1) * 100;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        return int.TryParse(statusCodePattern, out var expectedStatusCode) && statusCode == expectedStatusCode;");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    internal static T? DeserializeResponseContent<T>(string? responseContent)");
            builder.AppendLine("    {");
            builder.AppendLine("        return string.IsNullOrWhiteSpace(responseContent)");
            builder.AppendLine("            ? default");
            builder.AppendLine("            : JsonSerializer.Deserialize<T>(responseContent, SerializerOptions);");
            builder.AppendLine("    }");

            builder.AppendLine("}");
        }

        private void EmitTagClients(StringBuilder builder)
        {
            foreach (var tagGroup in model.TagGroups)
            {
                EmitTagClient(builder, tagGroup);
                builder.AppendLine();
            }
        }

        private void EmitTagClient(StringBuilder builder, TagGroup tagGroup)
        {
            EmitDocComment(
                builder,
                "    ",
                summary: $"{tagGroup.PropertyName} operations.",
                remarks: tagGroup.Description);
            builder.Append("public sealed class ").Append(tagGroup.ClassName).AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    private readonly HttpClient _httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("    private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
            }
            builder.AppendLine();
            var constructorParameters = string.Join(", ",
                new[] { "HttpClient httpClient" }.Concat(
                    _querySecuritySchemes
                        .Select(static scheme => $"string? {scheme.ParameterName}")));
            builder.Append("    internal ").Append(tagGroup.ClassName).Append('(').Append(constructorParameters).AppendLine(")");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient = httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("        ").Append(securityScheme.FieldName).Append(" = ").Append(securityScheme.ParameterName).AppendLine(";");
            }
            builder.AppendLine("    }");

            foreach (var operation in tagGroup.Operations)
            {
                builder.AppendLine();
                EmitOperation(builder, operation);
            }

            builder.AppendLine("}");
        }

        private void EmitClient(StringBuilder builder)
        {
            var constructorParameters = string.Join(", ", model.SecuritySchemes.Select(static scheme => scheme.ParameterDeclaration));

            EmitDocComment(
                builder,
                "    ",
                summary: model.Summary,
                remarks: model.Description);
            builder.Append("public partial class ").Append(model.ClientName).AppendLine(" : IDisposable");
            builder.AppendLine("{");
            builder.AppendLine("    private readonly HttpClient _httpClient;");
            foreach (var securityScheme in _querySecuritySchemes)
            {
                builder.Append("    private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
            }
            builder.AppendLine();
            builder.Append("    public ").Append(model.ClientName).Append('(').Append(constructorParameters).AppendLine(")");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient = new HttpClient();");
            if (Uri.TryCreate(model.ServerUrl, UriKind.Absolute, out _))
            {
                builder.Append("        _httpClient.BaseAddress = new Uri(\"").Append(EscapeStringLiteral(NormalizeBaseAddress(model.ServerUrl!))).AppendLine("\", UriKind.Absolute);");
            }

            foreach (var securityScheme in model.SecuritySchemes)
            {
                EmitSecuritySchemeInitialization(builder, securityScheme);
            }

            var constructorArguments = string.Join(", ",
                new[] { "_httpClient" }.Concat(
                    _querySecuritySchemes.Select(static scheme => scheme.FieldName)));
            foreach (var tagGroup in model.TagGroups)
            {
                builder.Append("        ").Append(tagGroup.PropertyName).Append(" = new ").Append(tagGroup.ClassName).Append('(').Append(constructorArguments).AppendLine(");");
            }

            builder.AppendLine("    }");
            builder.AppendLine();

            foreach (var tagGroup in model.TagGroups)
            {
                EmitDocComment(
                    builder,
                    "        ",
                    summary: $"{tagGroup.PropertyName} operations.",
                    remarks: tagGroup.Description);
                builder.Append("    public ").Append(tagGroup.ClassName).Append(' ').Append(tagGroup.PropertyName).AppendLine(" { get; }");
            }

            if (model.TagGroups.Count > 0)
            {
                builder.AppendLine();
            }

            builder.AppendLine("    public void Dispose()");
            builder.AppendLine("    {");
            builder.AppendLine("        _httpClient.Dispose();");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }
    }
}
