using System.Text;

namespace OpenApiWeaver;

public sealed partial class OpenApiWeaverSourceGenerator
{
    private sealed partial class ClientEmitter(ClientModel model)
    {
        private List<SecuritySchemeBinding> _querySecuritySchemes = null!;

        private bool _needsFormUrlEncoded;
        private bool _needsMultipartFormData;
        private bool _needsFormatParameter;

        public string Emit()
        {
            _querySecuritySchemes = model.SecuritySchemes.Where(static scheme => scheme.Location == SecuritySchemeLocation.Query).ToList();
            AnalyzeRequiredHelpers();

            var builder = new StringBuilder();
            var writer = new IndentedStringBuilder(builder);
            writer.AppendLine("// <auto-generated />");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("using System;");

            writer.AppendLine("using System.Collections.Generic;");

            if (_needsFormatParameter)
            {
                writer.AppendLine("using System.Globalization;");
            }

            writer.AppendLine("using System.Net.Http;");
            writer.AppendLine("using System.Net.Http.Json;");
            writer.AppendLine("using System.Text;");
            writer.AppendLine("using System.Text.Json;");
            writer.AppendLine("using System.Text.Json.Serialization;");
            writer.AppendLine("using System.Threading;");
            writer.AppendLine("using System.Threading.Tasks;");
            writer.AppendLine();

            if (!string.IsNullOrWhiteSpace(model.RootNamespace))
            {
                writer.Append("namespace ").Append(model.RootNamespace).AppendLine(";");
                writer.AppendLine();
            }

            EmitSchemas(writer);

            if (model.TagGroups.Count > 0)
            {
                EmitSupportTypes(writer);
                writer.AppendLine();
            }

            EmitTagClients(writer);
            EmitClient(writer);
            return builder.ToString();
        }

        private void AnalyzeRequiredHelpers()
        {
            if (_querySecuritySchemes.Count > 0)
            {
                _needsFormatParameter = true;
            }

            foreach (var tagGroup in model.TagGroups)
            {
                if (_needsFormUrlEncoded && _needsMultipartFormData && _needsFormatParameter)
                {
                    break;
                }

                foreach (var operation in tagGroup.Operations)
                {
                    if (_needsFormUrlEncoded && _needsMultipartFormData && _needsFormatParameter)
                    {
                        break;
                    }

                    var requestBody = operation.RequestBody;
                    if (requestBody is not null)
                    {
                        switch (requestBody.Kind)
                        {
                            case RequestBodyKind.FormUrlEncoded:
                                _needsFormUrlEncoded = true;
                                _needsFormatParameter = true;
                                break;
                            case RequestBodyKind.MultipartFormData:
                                _needsMultipartFormData = true;
                                _needsFormatParameter = true;
                                break;
                        }
                    }

                    if (operation.HasParameters)
                    {
                        _needsFormatParameter = true;
                    }
                }
            }
        }

        private static string NormalizeBaseAddress(string serverUrl)
        {
            var builder = new UriBuilder(new Uri(serverUrl, UriKind.Absolute));
            if (builder.Path.Length == 0)
            {
                builder.Path = "/";
            }
            else if (!builder.Path.EndsWith("/", StringComparison.Ordinal))
            {
                builder.Path += "/";
            }

            return builder.Uri.AbsoluteUri;
        }

        private void EmitSupportTypes(IndentedStringBuilder writer)
        {
            EmitExceptionTypes(writer);
            writer.AppendLine();

            EmitHelperClass(writer);
        }

        private static void EmitExceptionTypes(IndentedStringBuilder writer)
        {
            writer.AppendLine("public class OpenApiException : Exception");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("public OpenApiException(int statusCode, string? reasonPhrase, string? contentType, string? responseContent, Exception? innerException = null)");
                writer.AppendLine(": base(CreateMessage(statusCode, reasonPhrase), innerException)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("StatusCode = statusCode;");
                    writer.AppendLine("ReasonPhrase = reasonPhrase;");
                    writer.AppendLine("ContentType = contentType;");
                    writer.AppendLine("ResponseContent = responseContent;");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("public int StatusCode { get; }");
                writer.AppendLine();
                writer.AppendLine("public string? ReasonPhrase { get; }");
                writer.AppendLine();
                writer.AppendLine("public string? ContentType { get; }");
                writer.AppendLine();
                writer.AppendLine("public string? ResponseContent { get; }");
                writer.AppendLine();
                writer.AppendLine("private static string CreateMessage(int statusCode, string? reasonPhrase)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return string.IsNullOrWhiteSpace(reasonPhrase)");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("? $\"The HTTP request failed with status code {statusCode}.\"");
                        writer.AppendLine(": $\"The HTTP request failed with status code {statusCode} ({reasonPhrase}).\";");
                    }
                }

                writer.AppendLine("}");
            }

            writer.AppendLine("}");
            writer.AppendLine();
            writer.AppendLine("public class OpenApiException<TError> : OpenApiException");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("public OpenApiException(int statusCode, string? reasonPhrase, string? contentType, string? responseContent, TError? error, Exception? innerException = null)");
                writer.AppendLine(": base(statusCode, reasonPhrase, contentType, responseContent, innerException)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("Error = error;");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("public TError? Error { get; }");
            }

            writer.AppendLine("}");
        }

        private void EmitHelperClass(IndentedStringBuilder writer)
        {
            writer.AppendLine("internal static class OpenApiClientHelpers");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("internal static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web);");

                if (_needsFormatParameter)
                {
                    writer.AppendLine();
                    writer.AppendLine("internal static string FormatParameter(string? value) => value ?? string.Empty;");
                    writer.AppendLine();
                    writer.AppendLine("internal static string FormatParameter(JsonElement value) => value.ToString();");
                    writer.AppendLine();
                    writer.AppendLine("internal static string FormatParameter<T>(T value) where T : struct, IFormattable");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("return value.ToString(null, CultureInfo.InvariantCulture);");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("internal static string FormatParameter<T>(T? value) where T : struct, IFormattable");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("return value?.ToString(null, CultureInfo.InvariantCulture) ?? string.Empty;");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("internal static string FormatParameter(object? value)");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("return value switch");
                        writer.AppendLine("{");
                        using (writer.PushIndent())
                        {
                            writer.AppendLine("null => string.Empty,");
                            writer.AppendLine("IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),");
                            writer.AppendLine("_ => value.ToString() ?? string.Empty");
                        }

                        writer.AppendLine("};");
                    }

                    writer.AppendLine("}");
                }

                writer.AppendLine();
                writer.AppendLine("internal static void AppendQueryParameter(StringBuilder builder, ref bool hasQuery, string name, string value)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("builder.Append(hasQuery ? '&' : '?');");
                    writer.AppendLine("hasQuery = true;");
                    writer.AppendLine("builder.Append(name);");
                    writer.AppendLine("builder.Append('=');");
                    writer.AppendLine("builder.Append(Uri.EscapeDataString(value));");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static bool HasJsonContentType(string? contentType)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return !string.IsNullOrWhiteSpace(contentType) && contentType.Contains(\"json\", StringComparison.OrdinalIgnoreCase);");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static bool ResponseMatchesStatusCode(int statusCode, string statusCodePattern)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("if (string.Equals(statusCodePattern, \"default\", StringComparison.OrdinalIgnoreCase))");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("return true;");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("if (statusCodePattern.Length == 3");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("&& char.IsDigit(statusCodePattern[0])");
                        writer.AppendLine("&& statusCodePattern[1] is 'X' or 'x'");
                        writer.AppendLine("&& statusCodePattern[2] is 'X' or 'x')");
                    }

                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("var prefix = statusCodePattern[0] - '0';");
                        writer.AppendLine("return statusCode >= prefix * 100 && statusCode < (prefix + 1) * 100;");
                    }

                    writer.AppendLine("}");
                    writer.AppendLine();
                    writer.AppendLine("return int.TryParse(statusCodePattern, out var expectedStatusCode) && statusCode == expectedStatusCode;");
                }

                writer.AppendLine("}");
                writer.AppendLine();
                writer.AppendLine("internal static T? DeserializeResponseContent<T>(string? responseContent)");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("return string.IsNullOrWhiteSpace(responseContent)");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("? default");
                        writer.AppendLine(": JsonSerializer.Deserialize<T>(responseContent, SerializerOptions);");
                    }
                }

                writer.AppendLine("}");
            }

            writer.AppendLine("}");
        }

        private void EmitTagClients(IndentedStringBuilder writer)
        {
            foreach (var tagGroup in model.TagGroups)
            {
                EmitTagClient(writer, tagGroup);
                writer.AppendLine();
            }
        }

        private void EmitTagClient(IndentedStringBuilder writer, TagGroup tagGroup)
        {
            EmitDocComment(
                writer,
                summary: $"{tagGroup.PropertyName} operations.",
                remarks: tagGroup.Description);
            writer.Append("public sealed class ").Append(tagGroup.ClassName).AppendLine();
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("private readonly HttpClient _httpClient;");
                foreach (var securityScheme in model.SecuritySchemes)
                {
                    writer.Append("private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
                }

                writer.AppendLine();
                var constructorParameters = string.Join(", ",
                    new[] { "HttpClient httpClient" }.Concat(
                        model.SecuritySchemes
                            .Select(static scheme => $"string? {scheme.ParameterName}")));
                writer.Append("internal ").Append(tagGroup.ClassName).Append('(').Append(constructorParameters).AppendLine(")");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("_httpClient = httpClient;");
                    foreach (var securityScheme in model.SecuritySchemes)
                    {
                        writer.Append(securityScheme.FieldName).Append(" = ").Append(securityScheme.ParameterName).AppendLine(";");
                    }
                }

                writer.AppendLine("}");

                foreach (var operation in tagGroup.Operations)
                {
                    writer.AppendLine();
                    EmitOperation(writer, operation);
                }
            }

            writer.AppendLine("}");
        }

        private void EmitClient(IndentedStringBuilder writer)
        {
            var constructorParameters = string.Join(", ", model.SecuritySchemes.Select(static scheme => scheme.ParameterDeclaration));
            var injectedConstructorParameters = string.Join(", ", new[] { "HttpClient httpClient" }.Concat(model.SecuritySchemes.Select(static scheme => scheme.ParameterDeclaration)));
            var privateConstructorParameters = string.Join(", ", new[] { "HttpClient httpClient", "bool ownsHttpClient" }.Concat(model.SecuritySchemes.Select(static scheme => scheme.ParameterDeclaration)));
            var ownedConstructorArguments = string.Join(", ", new[] { "new HttpClient()", "true" }.Concat(model.SecuritySchemes.Select(static scheme => scheme.ParameterName)));
            var injectedConstructorArguments = string.Join(", ", new[] { "httpClient", "false" }.Concat(model.SecuritySchemes.Select(static scheme => scheme.ParameterName)));

            EmitDocComment(
                writer,
                summary: model.Summary,
                remarks: model.Description);
            writer.Append("public partial class ").Append(model.ClientName).AppendLine(" : IDisposable");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine("private readonly HttpClient _httpClient;");
                writer.AppendLine("private readonly bool _ownsHttpClient;");
                foreach (var securityScheme in model.SecuritySchemes)
                {
                    writer.Append("private readonly string? ").Append(securityScheme.FieldName).AppendLine(";");
                }

                writer.AppendLine();
                writer.Append("public ").Append(model.ClientName).Append('(').Append(constructorParameters).AppendLine(")");
                writer.Append("    : this(").Append(ownedConstructorArguments).AppendLine(")");
                writer.AppendLine("{");
                writer.AppendLine("}");
                writer.AppendLine();

                writer.Append("public ").Append(model.ClientName).Append('(').Append(injectedConstructorParameters).AppendLine(")");
                writer.Append("    : this(").Append(injectedConstructorArguments).AppendLine(")");
                writer.AppendLine("{");
                writer.AppendLine("}");
                writer.AppendLine();

                writer.Append("private ").Append(model.ClientName).Append('(').Append(privateConstructorParameters).AppendLine(")");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("_httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));");
                    writer.AppendLine("_ownsHttpClient = ownsHttpClient;");
                    if (Uri.TryCreate(model.ServerUrl, UriKind.Absolute, out _))
                    {
                        writer.AppendLine("if (_httpClient.BaseAddress is null)");
                        writer.AppendLine("{");
                        using (writer.PushIndent())
                        {
                            writer.Append("_httpClient.BaseAddress = new Uri(\"").Append(EscapeStringLiteral(NormalizeBaseAddress(model.ServerUrl!))).AppendLine("\", UriKind.Absolute);");
                        }

                        writer.AppendLine("}");
                    }

                    foreach (var securityScheme in model.SecuritySchemes)
                    {
                        EmitSecuritySchemeInitialization(writer, securityScheme);
                    }

                    var constructorArguments = string.Join(", ",
                        new[] { "_httpClient" }.Concat(
                            model.SecuritySchemes.Select(static scheme => scheme.FieldName)));
                    foreach (var tagGroup in model.TagGroups)
                    {
                        writer.Append(tagGroup.PropertyName).Append(" = new ").Append(tagGroup.ClassName).Append('(').Append(constructorArguments).AppendLine(");");
                    }
                }

                writer.AppendLine("}");
                writer.AppendLine();

                foreach (var tagGroup in model.TagGroups)
                {
                    EmitDocComment(
                        writer,
                        summary: $"{tagGroup.PropertyName} operations.",
                        remarks: tagGroup.Description);
                    writer.Append("public ").Append(tagGroup.ClassName).Append(' ').Append(tagGroup.PropertyName).AppendLine(" { get; }");
                }

                if (model.TagGroups.Count > 0)
                {
                    writer.AppendLine();
                }

                writer.AppendLine("public void Dispose()");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine("if (_ownsHttpClient)");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine("_httpClient.Dispose();");
                    }

                    writer.AppendLine("}");
                }

                writer.AppendLine("}");
            }

            writer.AppendLine("}");
        }
    }
}
