using System.Text;

namespace OpenApiWeaver;

public sealed partial class ClientGenerator
{
    private static partial class SupportTypesEmitter
    {
        public static string Emit(string rootNamespace)
        {
            var builder = new StringBuilder();
            var writer = new IndentedStringBuilder(builder);
            writer.AppendLine("// <auto-generated />");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("using System;");
            writer.AppendLine("using System.Collections.Generic;");
            writer.AppendLine("using System.Globalization;");
            writer.AppendLine("using System.Text;");
            writer.AppendLine("using System.Text.Json;");
            writer.AppendLine();

            if (!string.IsNullOrWhiteSpace(rootNamespace))
            {
                writer.Append("namespace ").Append(rootNamespace).AppendLine(";");
                writer.AppendLine();
            }

            EmitExceptionTypes(writer);
            writer.AppendLine();
            EmitHelperClass(writer);
            return builder.ToString();
        }
    }
}
