name: Publish NuGet

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.x

      - name: Extract package version
        id: package_version
        shell: bash
        run: |
          version="${GITHUB_REF_NAME#v}"
          echo "value=${version}" >> "$GITHUB_OUTPUT"

      - name: Restore
        run: dotnet restore src/OpenApiWeaver/OpenApiWeaver.csproj

      - name: Pack
        run: >-
          dotnet pack src/OpenApiWeaver/OpenApiWeaver.csproj
          --configuration Release
          --no-restore
          --output ./artifacts
          -p:Version=${{ steps.package_version.outputs.value }}

      - name: NuGet login
        id: login
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        with:
          user: shibayan

      - name: Push package
        run: >-
          dotnet nuget push "./artifacts/*.nupkg"
          --api-key "${{ steps.login.outputs.NUGET_API_KEY }}"
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate
